### ISSUE TITLE
Allow a single FastCS server to have multiple top level Controllers with different prefixes

### ISSUE THREAD

**Issue by coretl** [DiamondLightSource/FastCS#120]
For PandA the heirarchy of Controllers fits with FastCS:
- Top level Controller with PandABlocks-client connection, with PV prefix e.g. "BLxxI-EA-PANDA-01"
  - It creates SubControllers for each Block within it, appending suffix e.g. "PULSE1"
    - It has Attributes within it for each Field in the Block, appending the suffix e.g. "WIDTH"

For CATio we would like a different heirarchy
- Top level Controller with ADS connection, for status monitor and bus capture, with PV prefix e.g. "BLxxI-EA-ECAT-01"
- Peer Controllers for each coupler, e.g. "BLxxI-EA-ERIO-01"
  - SubControllers for each module attached to it, e.g. "ADC1"
    - Attributes for each parameter and channel of the module, e.g. "CHAN1"

We would need this if we ever did a PMAC in FastCS:
- Top level Controller with SSH connection, e.g. "BLxxI-MO-PMAC-01"
  - SubController per CS, e.g. "CS2"
- Peer Controllers for each axis, e.g. "BLxxI-MO-DCM-01:ROLL"
  - Attributes for it's parameters, e.g. "SETPOINT"

We need this top level PV heirarchy to be stable through axis moves so that we keep archiving and GUI build consistent.

## Acceptance Criteria
- We can make multiple Controllers with completely different PV prefixes

**Comment by coretl** [comment]
Hmm, how about merging all the files into a list then, and allowing per-controller overrides?
```yaml
# Common transport setup
transport:
  - graphql:
      host: localhost
      port: 8083
      log_level: info
  - epicsca:
  - epicspva:
# Per controller setup
controllers:
  - ip_settings:
      ip: "localhost"
      port: 25565
    num_ramp_controllers: 4
  transport_overrides:
    - epicsca:
        pv_prefix: GARYDEMO
      gui:
        title: Temperature Controller Demo (CA)
        output_path: ./demo_ca.bob
    - epicspva:
        pv_prefix: GARYDEMO
      gui:
        title: Temperature Controller Demo (PVA)
        output_path: ./demo_pva.bob
  - ip_settings:
      ip: "localhost"
      port: 25566
    num_ramp_controllers: 4
  transport_overrides:
    - epicsca:
        pv_prefix: GARYDEMO2
      gui:
        title: Temperature Controller Demo 2 (CA)
        output_path: ./demo2_ca.bob
    - epicspva:
        pv_prefix: GARYDEMO2
      gui:
        title: Temperature Controller Demo 2 (PVA)
        output_path: ./demo2_pva.bob
```

**Comment by gilesknap** [comment]
What I think I'm implementing (@coretl to verify this is what you want!)

- fastcs will allow multiple root controllers
  - each controller has an id which becomes the PV prefix
  - transports therefore no longer need PV prefix
- Thus the config file will become `fastcs.yaml` instead of `controller.yaml` and may container multiple controller definitions
  - This will become the preferred way to configure fastcs IOCs
- To this end the tutorial will be updated to a nice example using `fastcs.yaml`
  - I'll also take this as an oportunity to make the tutorial look more compelling with more sexy code.
- Additiona features to make use of yaml easier:-
  - Useful defaults such that the yaml can be kept to a minimum
  - e.g. Addition of a default CA/PVA transport with minimal config

**Comment by gilesknap** [comment]
Tom and I have agreed that it should look like this

```yaml
  controllers:                                                                                                                                                       
    - id: BLxxI-EA-ECAT-01                                                                                                                                     
      controller: { ... }                                                                                                                                            
    - id: BLxxI-EA-ERIO-01                                                                                                                                      
      controller: { ... }                                                                             
  transport:                          
    - epicsca:
    - epicspva:
    - rest:
```

- So id goes in the path for all transport types and represents the PV prefix for epics transports.
- Transports are responsible for making sure that all paths are unique
- controllers will also know their 'id' for reporting in logging etc.

**Comment by gilesknap** [comment]
@coretl 

A revision while planning: switching from list-with-id-field to dict-keyed-by-id for the controllers: block:  

```yaml                                                                                                                                                                                                                             
  controllers:                        
    BLxxI-EA-ECAT-01:            
      type: ECATController    
      controller: { ... }             
    BLxxI-EA-ERIO-01:                                                                                        
      type: ERIOController  
      controller: { ... }             
```

  Reasoning:                                                                                                                                                                                                                 
  - YAML structurally enforces id uniqueness — no manual check needed.
  - Maps 1:1 to the runtime shell context (controllers: dict[str, Controller]).                                                                                                                                              
  - Removes the id: boilerplate.                                                                       
  - Insertion order is preserved.

**Comment by gilesknap** [comment]
Small revision while planning: switching from list-with-`id`-field to **dict-keyed-by-id** for the `controllers:` block:

```yaml
controllers:
  BLxxI-EA-ECAT-01:
    type: ECATController
    controller: { ... }
  BLxxI-EA-ERIO-01:
    type: ERIOController
    controller: { ... }
```

instead of:

```yaml
controllers:
  - id: BLxxI-EA-ECAT-01
    type: ECATController
    controller: { ... }
  - id: BLxxI-EA-ERIO-01
    ...
```

Reasoning:
- YAML structurally enforces id uniqueness — no manual check needed.
- Maps 1:1 to the runtime shell context (`controllers: dict[str, Controller]`).
- Removes the `id:` boilerplate.
- Insertion order is preserved (ruamel safe loader returns ordered dicts).

Other outcomes from today's design pass that aren't in writing yet:
- `launch()` takes a list of `Controller` classes; YAML entries pick the class via a `type:` field (defaults to class `__name__`); single-class registrations can elide `type:`.
- The `id` lives on the `Controller` instance (set after construction by the launcher) and becomes the first segment of every transport path. EPICS-style PV prefixes via `path[0]` verbatim, sub-controller path segments still go through `snake_to_pascal`.
- Each transport validates `id` against its own naming rules at `connect()` time and fails fast on illegal characters — no silent name mangling. Acknowledged limitation: mixing transports with incompatible naming rules forces a lowest-common-denominator id.
- `EpicsIOCOptions.pv_prefix` (and the `EpicsIOCOptions` dataclass) gets removed entirely.
- One softioc per process, N PVI roots — `EpicsCAIOC` (and PVA equivalent) takes the full list of `ControllerAPI`s and iterates.
- Single Controller still works as a list-of-one. No backwards-compat path for the old singular `controller:` YAML form — clean break, single schema.
- Shell context: `controllers: dict[id, Controller]`, with a `Controller.api` back-pointer so `controllers["BLxxI-EA-ECAT-01"].api.path` works without a parallel `controller_apis` dict.

Full PRD with user stories, implementation decisions, and testing plan: #351

Shout if any of this looks wrong before I start writing code.

**Comment by coretl** [comment]
I agree with N PVI roots, but we still need to make `index.bob` with buttons for `BLxxI-EA-ECAT-01` and `BLxxI-EA-ERIO-01` in the same way as a C++ IOC.

**Comment by gilesknap** [comment]
@coretl do you mean that if we change the path in a given subcontroller, that needs to then be promoted to a button in index.bob. (if we use the default path then its part of the pre-existing bob file hierarchy). Am I understanding you?

**Comment by coretl** [comment]
Yes, the path heirarchy should be the button heirarchy on the screens and the PVI heirarchy.

E.g. for ethercat, the controller heirarchy would be something like:
```
- ECATController(path=["BLxxI-EA-ECAT-01"])
  # Populated at runtime
  - ERIOController(path=["BLxxI-EA-ERIO-01"])
  - ENodeController(path=["BLxxI-EA-ERIO-01", "adc1"])
  - ERIOController(path=["BLxxI-EA-ERIO-02"])
  - ENodeController(path=["BLxxI-EA-ERIO-02", "dac1"])
  ...
```
which would make a PVI hierarchy:
```
BLxxI-EA-ECAT-01:PVI:

BLxxI-EA-ERIO-01:PVI:
    adc1: BLxxI-EA-ERIO-01:ADC1:PVI

BLxxI-EA-ERIO-02:PVI:
    adc1: BLxxI-EA-ERIO-02:DAC1:PVI
```
which would make a screen hierarchy:
```
index.bob:
  BLxxI-EA-ECAT-01:
  BLxxI-EA-ERIO-01:
    ADC1:
  BLxxI-EA-ERIO-02:
    DAC1:
```
